[package]
name = "helm"
version = "0.2.73"
description = "HELM - Personal Assistant for Engineers"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.89.0"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.10.3", features = [] }
tauri-plugin-log = "2"
tauri-plugin-notification = "2.3.3"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
rfd = "0.15"
command-group = "5.0.1"
sha2 = "0.10"
